# Default user accounts.  These should be changed for apps in production.

default_user_1:
  uid: 'admin'
  email: 'admin@example.com'
  first_name: 'Admin'
  last_name: 'User'
  is_admin: true
  account_type: 'standard'

default_user_2:
  uid: 'test'
  email: 'test@example.com'
  first_name: 'Test'
  last_name: 'User'
  is_admin: false
  account_type: 'standard'

default_user_3:
  uid: 'service'
  email: 'service@example.com'
  first_name: 'Service'
  last_name: 'User'
  is_admin: false
  account_type: 'service'

default_user_4:
  uid: 'derivativo'
  email: 'derivativo@example.com'
  first_name: 'Derivativo'
  last_name: 'User'
  is_admin: true
  account_type: 'service'
  api_key: 'derivativo-api-key'
