default: &default
  user: apitest
  password: apitest
  shoulder:
    ark: 'ark:99999/fk4'
    doi: 'doi:10.5072/FK2'
  ezid_test_user: apitest
  ezid_test_password: apitest
  ezid_test_shoulder:
    ark: 'ark:99999/fk4'
    doi: 'doi:10.5072/FK2'
  url: 'https://ezid.cdlib.org'
  ezid_publisher: 'Columbia University'
  datacite:
    genre_to_resource_type_mapping:
      'http://vocab.getty.edu/aat/300048715':
        attribute_general: Text
        content: Article
development:
  <<: *default
test:
  <<: *default
