default: &default
  version: 6.3.0
  download_dir: <%= Rails.root.join('tmp', 'solr-download') %>
  verbose: false
  managed: true
  solr_options:
    "a" : "-Djetty.host=127.0.0.1"

development:
  <<: *default
  port: 8983
  instance_dir: <%= Rails.root.join('tmp', 'solr-development') %>
  collection:
    - name: 'hyacinth-development'
      dir: <%= Rails.root.join('spec', 'fixtures', 'solr_cores', 'hyacinth-solr-6-3', 'conf') %>
    - name: 'terms-development'
      dir: <%= Rails.root.join('spec', 'fixtures', 'solr_cores', 'terms-solr-6', 'conf') %>

test:
  <<: *default
  port: 9983
  instance_dir: <%= Rails.root.join('tmp', 'solr-test') %>
  collection:
    - name: 'hyacinth-test'
      dir: <%= Rails.root.join('spec', 'fixtures', 'solr_cores', 'hyacinth-solr-6-3', 'conf') %>
    - name: 'terms-test'
      dir: <%= Rails.root.join('spec', 'fixtures', 'solr_cores', 'terms-solr-6', 'conf') %>
